framework:
    cache:
        prefix_seed: socnet

        app: my_cache_pool

        pools:
            my_cache_pool:
                default_lifetime: 31536000  # Один год
                tags: true
                adapters:
                    - cache.adapter.array
                    - {name: cache.adapter.redis, provider: 'redis://%env(resolve:REDIS_HOST)%'}
